/**
 * The curated exercise catalogue.
 *
 * `source` refers to an entry in the free-exercise-db dataset (public domain),
 * from which the artwork and the long instructions are taken. Everything else
 * — the family, the load increment, which equipment profiles the movement
 * belongs to, and the short coaching cues — is defined here.
 *
 *   family:     drives the progression step (see src/lib/progression.ts)
 *   increment:  kilograms added when every prescribed repetition is completed
 *   profiles:   equipment profiles in which the movement can be programmed
 *   cues:       three short reminders, shown on the training screen
 */

export const CATALOGUE = [
  /* ------------------------------------------------------ barbell, gym */
  {
    slug: "barbell-squat",
    source: "Barbell_Squat",
    name: "Barbell Back Squat",
    muscle: "quadriceps",
    family: "lower_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Bar on the shelf of your upper back, not on your neck.",
      "Break at the hips and knees together, knees tracking over the toes.",
      "Depth: hip crease below the top of the knee, back stays braced.",
    ],
  },
  {
    slug: "barbell-bench-press",
    source: "Barbell_Bench_Press_-_Medium_Grip",
    name: "Barbell Bench Press",
    muscle: "chest",
    family: "upper_compound",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "Shoulder blades pinned back and down into the bench.",
      "Bar touches the lower chest, elbows about 45 degrees from the body.",
      "Use a spotter or the safety pins on every working set.",
    ],
  },
  {
    slug: "barbell-row",
    source: "Bent_Over_Barbell_Row",
    name: "Bent-Over Barbell Row",
    muscle: "middle back",
    family: "upper_compound",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "Hinge to roughly 45 degrees and keep the back flat throughout.",
      "Pull the bar to the lower ribs, elbows past the torso.",
      "No jerking with the lower back — the torso angle stays fixed.",
    ],
  },
  {
    slug: "barbell-deadlift",
    source: "Barbell_Deadlift",
    name: "Deadlift",
    muscle: "lower back",
    family: "lower_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Bar over mid-foot, shins almost touching before you pull.",
      "Take the slack out of the bar, then push the floor away.",
      "Back flat from start to finish; stop the set if it rounds.",
    ],
  },
  {
    slug: "overhead-press",
    source: "Standing_Military_Press",
    name: "Overhead Press",
    muscle: "shoulders",
    family: "upper_compound",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "Bar rests on the front delts, elbows slightly ahead of the bar.",
      "Squeeze the glutes so the lower back does not arch.",
      "Push the head through once the bar passes the forehead.",
    ],
  },
  {
    slug: "romanian-deadlift",
    source: "Romanian_Deadlift",
    name: "Romanian Deadlift",
    muscle: "hamstrings",
    family: "lower_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Soft knees, then push the hips backwards, not down.",
      "Bar stays in contact with the thighs the whole way.",
      "Stop where the hamstrings stretch, before the back rounds.",
    ],
  },
  {
    slug: "front-squat",
    source: "Front_Barbell_Squat",
    name: "Front Squat",
    muscle: "quadriceps",
    family: "lower_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Elbows high; the bar sits on the front delts, not the hands.",
      "Stay upright and drive the elbows up out of the bottom.",
      "If the elbows drop, the weight is too heavy.",
    ],
  },
  {
    slug: "incline-bench-press",
    source: "Barbell_Incline_Bench_Press_-_Medium_Grip",
    name: "Incline Bench Press",
    muscle: "chest",
    family: "upper_compound",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "Bench at about 30 degrees, no higher.",
      "Bar touches the upper chest, just below the collarbone.",
      "Keep the shoulder blades retracted against the pad.",
    ],
  },
  {
    slug: "barbell-hip-thrust",
    source: "Barbell_Hip_Thrust",
    name: "Barbell Hip Thrust",
    muscle: "glutes",
    family: "lower_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Bench under the shoulder blades, pad on the hips.",
      "Ribs down, chin tucked; finish with the torso parallel to the floor.",
      "Squeeze the glutes at the top rather than arching the back.",
    ],
  },

  /* --------------------------------------------------- dumbbell, gym */
  {
    slug: "goblet-squat",
    source: "Goblet_Squat",
    name: "Goblet Squat",
    muscle: "quadriceps",
    family: "lower_compound",
    increment: 2.5,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Hold the bell against the chest, elbows inside the knees.",
      "Sit straight down between the hips, heels flat.",
      "Chest tall — the weight will pull you forward if you let it.",
    ],
  },
  {
    slug: "dumbbell-bench-press",
    source: "Dumbbell_Bench_Press",
    name: "Dumbbell Bench Press",
    muscle: "chest",
    family: "upper_compound",
    increment: 2,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Bring the dumbbells to the bench with the knees, not the shoulders.",
      "Lower until the elbows are level with the torso.",
      "Wrists stacked over the elbows throughout.",
    ],
  },
  {
    slug: "dumbbell-shoulder-press",
    source: "Dumbbell_Shoulder_Press",
    name: "Dumbbell Shoulder Press",
    muscle: "shoulders",
    family: "upper_compound",
    increment: 2,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Start with the dumbbells at ear height, palms forward.",
      "Press slightly inward until they nearly touch overhead.",
      "Brace the abdomen so the lower back stays neutral.",
    ],
  },
  {
    slug: "dumbbell-row",
    source: "One-Arm_Dumbbell_Row",
    name: "One-Arm Dumbbell Row",
    muscle: "middle back",
    family: "upper_compound",
    increment: 2,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Flat back, hand and knee supported on the bench.",
      "Pull the dumbbell towards the hip, elbow close to the ribs.",
      "No twisting of the torso to move more weight.",
    ],
  },
  {
    slug: "dumbbell-lunge",
    source: "Dumbbell_Lunges",
    name: "Dumbbell Lunge",
    muscle: "quadriceps",
    family: "accessory",
    increment: 2,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Step out far enough that the front shin stays near vertical.",
      "Lower until the back knee is just off the floor.",
      "Push through the front heel to return.",
    ],
  },
  {
    slug: "split-squat",
    source: "Split_Squat_with_Dumbbells",
    name: "Split Squat",
    muscle: "quadriceps",
    family: "accessory",
    increment: 2,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Feet stay planted; only the knees and hips move.",
      "Torso upright, weight through the front foot.",
      "Complete every repetition on one leg before switching.",
    ],
  },
  {
    slug: "lateral-raise",
    source: "Side_Lateral_Raise",
    name: "Lateral Raise",
    muscle: "shoulders",
    family: "accessory",
    increment: 1,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Small bend in the elbows, held constant.",
      "Raise to shoulder height, no higher.",
      "Light weight; if you swing, it is too heavy.",
    ],
  },
  {
    slug: "dumbbell-curl",
    source: "Dumbbell_Bicep_Curl",
    name: "Dumbbell Curl",
    muscle: "biceps",
    family: "accessory",
    increment: 1,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Elbows stay at the sides.",
      "Curl without swinging the torso.",
      "Lower under control, all the way down.",
    ],
  },
  {
    slug: "hammer-curl",
    source: "Hammer_Curls",
    name: "Hammer Curl",
    muscle: "biceps",
    family: "accessory",
    increment: 1,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Palms face each other for the whole set.",
      "Elbows pinned to the ribs.",
      "Control the descent; do not drop the weight.",
    ],
  },
  {
    slug: "overhead-triceps-extension",
    source: "Dumbbell_One-Arm_Triceps_Extension",
    name: "Overhead Triceps Extension",
    muscle: "triceps",
    family: "accessory",
    increment: 1,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Upper arm stays vertical and still.",
      "Lower behind the head until the forearm touches the biceps.",
      "Stop if the elbow feels pinched.",
    ],
  },

  /* ------------------------------------------------------ machines, gym */
  {
    slug: "lat-pulldown",
    source: "Wide-Grip_Lat_Pulldown",
    name: "Lat Pulldown",
    muscle: "lats",
    family: "upper_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Thighs locked under the pad before the first repetition.",
      "Pull the bar to the collarbone, elbows down and back.",
      "Lean back slightly, but keep the torso still.",
    ],
  },
  {
    slug: "seated-cable-row",
    source: "Seated_Cable_Rows",
    name: "Seated Cable Row",
    muscle: "middle back",
    family: "upper_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Chest tall, slight forward lean at the stretch only.",
      "Pull the handle to the navel, squeezing the shoulder blades.",
      "No rocking backwards and forwards.",
    ],
  },
  {
    slug: "leg-press",
    source: "Leg_Press",
    name: "Leg Press",
    muscle: "quadriceps",
    family: "lower_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Feet shoulder width, mid-foot on the platform.",
      "Lower until the knees reach about 90 degrees.",
      "Never let the lower back lift off the pad.",
    ],
  },
  {
    slug: "leg-extension",
    source: "Leg_Extensions",
    name: "Leg Extension",
    muscle: "quadriceps",
    family: "accessory",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Knee joint lined up with the pivot of the machine.",
      "Extend smoothly, pause briefly at the top.",
      "Lower under control rather than letting the stack drop.",
    ],
  },
  {
    slug: "lying-leg-curl",
    source: "Lying_Leg_Curls",
    name: "Lying Leg Curl",
    muscle: "hamstrings",
    family: "accessory",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Hips stay flat on the pad.",
      "Curl the heels towards the glutes.",
      "Three seconds down on every repetition.",
    ],
  },
  {
    slug: "chest-press-machine",
    source: "Leverage_Chest_Press",
    name: "Chest Press Machine",
    muscle: "chest",
    family: "upper_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Set the seat so the handles line up with the mid-chest.",
      "Press without locking the elbows hard.",
      "Shoulder blades stay back against the pad.",
    ],
  },
  {
    slug: "face-pull",
    source: "Face_Pull",
    name: "Face Pull",
    muscle: "shoulders",
    family: "accessory",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "Cable set at face height.",
      "Pull the rope towards the eyes, hands finishing wide.",
      "Light weight, high repetitions — this one is for the shoulders.",
    ],
  },
  {
    slug: "triceps-pushdown",
    source: "Triceps_Pushdown",
    name: "Triceps Pushdown",
    muscle: "triceps",
    family: "accessory",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "Elbows locked at the sides throughout.",
      "Extend fully, then return only to 90 degrees.",
      "Stand tall; no leaning over the bar.",
    ],
  },
  {
    slug: "calf-raise",
    source: "Standing_Calf_Raises",
    name: "Standing Calf Raise",
    muscle: "calves",
    family: "accessory",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Full stretch at the bottom, full contraction at the top.",
      "Pause for one second at the top of each repetition.",
      "Keep the knees straight but not locked.",
    ],
  },
  {
    slug: "cable-crunch",
    source: "Cable_Crunch",
    name: "Cable Crunch",
    muscle: "abdominals",
    family: "accessory",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "Kneel far enough from the stack to feel tension at the start.",
      "Curl the ribs towards the hips; the hips do not move.",
      "Return slowly rather than being pulled up.",
    ],
  },

  /* --------------------------------------------------------- bodyweight */
  {
    slug: "pull-up",
    source: "Pullups",
    name: "Pull-Up",
    muscle: "lats",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Full hang at the bottom, shoulders active.",
      "Chin clears the bar without craning the neck.",
      "Use a band or the assisted machine while you build strength.",
    ],
  },
  {
    slug: "chin-up",
    source: "Chin-Up",
    name: "Chin-Up",
    muscle: "biceps",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Palms facing you, hands about shoulder width.",
      "Pull the elbows down towards the ribs.",
      "Control the way down; that half builds the strength.",
    ],
  },
  {
    slug: "dip",
    source: "Dips_-_Triceps_Version",
    name: "Triceps Dip",
    muscle: "triceps",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym"],
    cues: [
      "Torso close to upright, elbows tracking backwards.",
      "Lower until the upper arms are parallel to the floor.",
      "Stop the set if the front of the shoulder pinches.",
    ],
  },
  {
    slug: "push-up",
    source: "Pushups",
    name: "Push-Up",
    muscle: "chest",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym", "hotel", "home_minimal"],
    cues: [
      "Straight line from head to heels; squeeze the glutes.",
      "Elbows at about 45 degrees, not flared to the sides.",
      "Chest to the floor, then push the floor away.",
    ],
  },
  {
    slug: "bodyweight-squat",
    source: "Bodyweight_Squat",
    name: "Bodyweight Squat",
    muscle: "quadriceps",
    family: "bodyweight",
    increment: 0,
    profiles: ["hotel", "home_minimal"],
    cues: [
      "Feet shoulder width, toes slightly out.",
      "Sit back and down, heels stay on the floor.",
      "Slow on the way down, three seconds.",
    ],
  },
  {
    slug: "walking-lunge",
    source: "Bodyweight_Walking_Lunge",
    name: "Walking Lunge",
    muscle: "quadriceps",
    family: "bodyweight",
    increment: 0,
    profiles: ["hotel", "home_minimal"],
    cues: [
      "Long steps, torso upright.",
      "Back knee lightly touches the floor.",
      "Count repetitions per leg, not in total.",
    ],
  },
  {
    slug: "glute-bridge",
    source: "Butt_Lift_Bridge",
    name: "Glute Bridge",
    muscle: "glutes",
    family: "bodyweight",
    increment: 0,
    profiles: ["hotel", "home_minimal"],
    cues: [
      "Heels close to the glutes, toes up.",
      "Drive through the heels and squeeze at the top.",
      "Ribs down — do not arch the lower back.",
    ],
  },
  {
    slug: "inverted-row",
    source: "Inverted_Row",
    name: "Inverted Row",
    muscle: "middle back",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym", "hotel", "home_minimal"],
    cues: [
      "Body in a straight line, heels on the floor.",
      "Pull the chest to the bar or the edge of the table.",
      "Walk the feet in to make it easier.",
    ],
  },
  {
    slug: "pike-push-up",
    source: "Pushups",
    name: "Pike Push-Up",
    muscle: "shoulders",
    family: "bodyweight",
    increment: 0,
    profiles: ["hotel", "home_minimal"],
    cues: [
      "Hips high, body in an inverted V.",
      "Lower the crown of the head towards the floor.",
      "Elevate the feet on a bed or chair to make it harder.",
    ],
  },
  {
    slug: "plank",
    source: "Plank",
    name: "Plank",
    muscle: "abdominals",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym", "hotel", "home_minimal"],
    cues: [
      "Elbows under the shoulders, forearms flat.",
      "Squeeze the glutes and tuck the ribs down.",
      "Hold for time; stop when the hips start to sag.",
    ],
  },
  {
    slug: "side-plank",
    source: "Side_Bridge",
    name: "Side Plank",
    muscle: "abdominals",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym", "hotel", "home_minimal"],
    cues: [
      "Elbow under the shoulder, body in one line.",
      "Lift the hips and hold; breathe normally.",
      "Equal time on both sides.",
    ],
  },
  {
    slug: "hanging-leg-raise",
    source: "Hanging_Leg_Raise",
    name: "Hanging Leg Raise",
    muscle: "abdominals",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym"],
    cues: [
      "Hang without swinging.",
      "Curl the pelvis up rather than only lifting the legs.",
      "Bend the knees to make it easier.",
    ],
  },
  {
    slug: "mountain-climber",
    source: "Mountain_Climbers",
    name: "Mountain Climber",
    muscle: "abdominals",
    family: "bodyweight",
    increment: 0,
    profiles: ["hotel", "home_minimal"],
    cues: [
      "Hands under the shoulders, hips level.",
      "Drive the knees towards the chest one at a time.",
      "Steady pace; the hips should not bounce.",
    ],
  },
  {
    slug: "superman",
    source: "Superman",
    name: "Superman Hold",
    muscle: "lower back",
    family: "bodyweight",
    increment: 0,
    profiles: ["hotel", "home_minimal"],
    cues: [
      "Face down, arms extended forward.",
      "Lift the chest and thighs a few centimetres only.",
      "Look at the floor to keep the neck neutral.",
    ],
  },
];
