/**
 * Catálogo de exercícios seleccionado.
 *
 * `source` refere-se a uma entrada do conjunto de dados free-exercise-db
 * (domínio público), de onde vêm as imagens. Tudo o resto — a família, o
 * incremento de carga, os perfis de equipamento e as indicações técnicas — é
 * definido aqui.
 *
 *   family:     define o passo de progressão (ver src/lib/progression.ts)
 *   increment:  quilos acrescentados quando todas as repetições são feitas
 *   profiles:   perfis de equipamento em que o exercício pode ser prescrito
 *   cues:       três lembretes curtos, mostrados no ecrã de treino
 *   timed:      a série é uma isometria; os campos de repetições são segundos
 *   perSide:    o movimento é unilateral; regista-se o total das duas pernas
 *               ou dos dois braços e a aplicação mostra a divisão
 */

export const CATALOGUE = [
  /* ------------------------------------------------------ barra, ginásio */
  {
    slug: "barbell-squat",
    source: "Barbell_Squat",
    name: "Agachamento com Barra",
    muscle: "quadríceps",
    family: "lower_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "A barra assenta nos trapézios, nunca no pescoço.",
      "Desce a dobrar as ancas e os joelhos ao mesmo tempo, joelhos na linha dos pés.",
      "Desce até a anca ficar abaixo do joelho, com o tronco firme.",
    ],
  },
  {
    slug: "barbell-bench-press",
    source: "Barbell_Bench_Press_-_Medium_Grip",
    name: "Supino com Barra",
    muscle: "peito",
    family: "upper_compound",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "Omoplatas juntas e encostadas ao banco.",
      "A barra toca no peito baixo, cotovelos a cerca de 45 graus.",
      "Usa sempre ajuda ou as barras de segurança nas séries pesadas.",
    ],
  },
  {
    slug: "barbell-row",
    source: "Bent_Over_Barbell_Row",
    name: "Remada Curvada com Barra",
    muscle: "costas",
    family: "upper_compound",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "Inclina o tronco cerca de 45 graus e mantém as costas direitas.",
      "Puxa a barra às costelas de baixo, cotovelos para trás.",
      "Não dês impulso com a lombar: o tronco fica parado.",
    ],
  },
  {
    slug: "barbell-deadlift",
    source: "Barbell_Deadlift",
    name: "Levantamento Terra",
    muscle: "lombar",
    family: "lower_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Barra sobre o meio do pé, quase a tocar nas canelas.",
      "Tira a folga da barra e empurra o chão com os pés.",
      "Costas direitas do início ao fim; pára a série se curvarem.",
    ],
  },
  {
    slug: "overhead-press",
    source: "Standing_Military_Press",
    name: "Desenvolvimento Militar",
    muscle: "ombros",
    family: "upper_compound",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "A barra assenta nos deltóides, cotovelos ligeiramente à frente.",
      "Aperta os glúteos para a lombar não arquear.",
      "Passa a cabeça à frente da barra assim que ela sobe acima da testa.",
    ],
  },
  {
    slug: "romanian-deadlift",
    source: "Romanian_Deadlift",
    name: "Levantamento Terra Romeno",
    muscle: "isquiotibiais",
    family: "lower_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Joelhos levemente destravados e ancas para trás, não para baixo.",
      "A barra desliza junto às coxas durante todo o movimento.",
      "Pára onde sentes o alongamento atrás da coxa, antes de curvar as costas.",
    ],
  },
  {
    slug: "front-squat",
    source: "Front_Barbell_Squat",
    name: "Agachamento Frontal",
    muscle: "quadríceps",
    family: "lower_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Cotovelos altos: a barra assenta nos ombros, não nas mãos.",
      "Tronco direito e cotovelos a subir na saída do fundo.",
      "Se os cotovelos caem, o peso é demasiado.",
    ],
  },
  {
    slug: "incline-bench-press",
    source: "Barbell_Incline_Bench_Press_-_Medium_Grip",
    name: "Supino Inclinado",
    muscle: "peito",
    family: "upper_compound",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "Banco a cerca de 30 graus, não mais.",
      "A barra toca no peito alto, logo abaixo das clavículas.",
      "Mantém as omoplatas juntas contra o banco.",
    ],
  },
  {
    slug: "barbell-hip-thrust",
    source: "Barbell_Hip_Thrust",
    name: "Elevação Pélvica com Barra",
    muscle: "glúteos",
    family: "lower_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Banco por baixo das omoplatas e almofada sobre a anca.",
      "Costelas em baixo e queixo recolhido; acaba com o tronco paralelo ao chão.",
      "Aperta os glúteos no topo em vez de arquear a lombar.",
    ],
  },

  /* --------------------------------------------------- halteres, ginásio */
  {
    slug: "goblet-squat",
    source: "Goblet_Squat",
    name: "Agachamento Goblet",
    muscle: "quadríceps",
    family: "lower_compound",
    increment: 2.5,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Segura o peso junto ao peito, cotovelos por dentro dos joelhos.",
      "Desce a direito entre as ancas, calcanhares no chão.",
      "Peito alto: o peso puxa-te para a frente se deixares.",
    ],
  },
  {
    slug: "dumbbell-bench-press",
    source: "Dumbbell_Bench_Press",
    name: "Supino com Halteres",
    muscle: "peito",
    family: "upper_compound",
    increment: 2,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Leva os halteres ao banco com os joelhos, não com os ombros.",
      "Desce até os cotovelos ficarem à altura do tronco.",
      "Pulsos sempre por cima dos cotovelos.",
    ],
  },
  {
    slug: "dumbbell-shoulder-press",
    source: "Dumbbell_Shoulder_Press",
    name: "Desenvolvimento com Halteres",
    muscle: "ombros",
    family: "upper_compound",
    increment: 2,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Começa com os halteres à altura das orelhas, palmas para a frente.",
      "Sobe ligeiramente para dentro até quase se tocarem em cima.",
      "Abdominal contraído para a lombar ficar neutra.",
    ],
  },
  {
    slug: "dumbbell-row",
    perSide: true,
    source: "One-Arm_Dumbbell_Row",
    name: "Remada Unilateral com Haltere",
    muscle: "costas",
    family: "upper_compound",
    increment: 2,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Costas direitas, mão e joelho apoiados no banco.",
      "Puxa o haltere em direcção à anca, cotovelo junto às costelas.",
      "Não rodes o tronco para levantar mais peso.",
    ],
  },
  {
    slug: "dumbbell-lunge",
    perSide: true,
    source: "Dumbbell_Lunges",
    name: "Afundo com Halteres",
    muscle: "quadríceps",
    family: "accessory",
    increment: 2,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Passo suficientemente longo para a canela da frente ficar vertical.",
      "Desce até o joelho de trás quase tocar no chão.",
      "Sobe a empurrar com o calcanhar da frente.",
    ],
  },
  {
    slug: "split-squat",
    perSide: true,
    source: "Split_Squat_with_Dumbbells",
    name: "Agachamento Dividido",
    muscle: "quadríceps",
    family: "accessory",
    increment: 2,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Os pés ficam parados; só se movem joelhos e ancas.",
      "Tronco direito, peso na perna da frente.",
      "Faz todas as repetições de uma perna antes de trocar.",
    ],
  },
  {
    slug: "lateral-raise",
    source: "Side_Lateral_Raise",
    name: "Elevações Laterais",
    muscle: "ombros",
    family: "accessory",
    increment: 1,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Cotovelos com uma ligeira flexão, sempre igual.",
      "Sobe até à altura dos ombros, não mais.",
      "Peso leve: se tens de balançar, é pesado demais.",
    ],
  },
  {
    slug: "dumbbell-curl",
    source: "Dumbbell_Bicep_Curl",
    name: "Curl de Bíceps com Halteres",
    muscle: "bíceps",
    family: "accessory",
    increment: 1,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Cotovelos encostados ao tronco.",
      "Sobe sem balançar o corpo.",
      "Desce devagar e até ao fim.",
    ],
  },
  {
    slug: "hammer-curl",
    source: "Hammer_Curls",
    name: "Curl Martelo",
    muscle: "bíceps",
    family: "accessory",
    increment: 1,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Palmas viradas uma para a outra durante toda a série.",
      "Cotovelos fixos junto às costelas.",
      "Controla a descida; não largues o peso.",
    ],
  },
  {
    slug: "overhead-triceps-extension",
    perSide: true,
    source: "Dumbbell_One-Arm_Triceps_Extension",
    name: "Extensão de Tríceps Acima da Cabeça",
    muscle: "tríceps",
    family: "accessory",
    increment: 1,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "O braço fica vertical e parado.",
      "Desce atrás da cabeça até o antebraço tocar no bíceps.",
      "Pára se sentires o cotovelo a picar.",
    ],
  },

  /* ------------------------------------------------------ máquinas, ginásio */
  {
    slug: "lat-pulldown",
    source: "Wide-Grip_Lat_Pulldown",
    name: "Puxada na Polia Alta",
    muscle: "dorsais",
    family: "upper_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Coxas presas debaixo do apoio antes da primeira repetição.",
      "Puxa a barra às clavículas, cotovelos para baixo e para trás.",
      "Inclina-te ligeiramente para trás, mas mantém o tronco parado.",
    ],
  },
  {
    slug: "seated-cable-row",
    source: "Seated_Cable_Rows",
    name: "Remada Sentada na Polia",
    muscle: "costas",
    family: "upper_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Peito alto; só te inclinas à frente no alongamento.",
      "Puxa o pega ao umbigo, a juntar as omoplatas.",
      "Sem balanço para a frente e para trás.",
    ],
  },
  {
    slug: "leg-press",
    source: "Leg_Press",
    name: "Prensa de Pernas",
    muscle: "quadríceps",
    family: "lower_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Pés à largura dos ombros, a meio da plataforma.",
      "Desce até os joelhos ficarem a cerca de 90 graus.",
      "A lombar nunca levanta do apoio.",
    ],
  },
  {
    slug: "leg-extension",
    source: "Leg_Extensions",
    name: "Extensão de Pernas",
    muscle: "quadríceps",
    family: "accessory",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Joelho alinhado com o eixo da máquina.",
      "Estica sem pancada e faz uma pausa curta no topo.",
      "Desce controlado em vez de deixar cair o peso.",
    ],
  },
  {
    slug: "lying-leg-curl",
    source: "Lying_Leg_Curls",
    name: "Flexão de Pernas Deitado",
    muscle: "isquiotibiais",
    family: "accessory",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "As ancas ficam encostadas ao apoio.",
      "Leva os calcanhares aos glúteos.",
      "Três segundos a descer em cada repetição.",
    ],
  },
  {
    slug: "chest-press-machine",
    source: "Leverage_Chest_Press",
    name: "Press de Peito na Máquina",
    muscle: "peito",
    family: "upper_compound",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Ajusta o banco para as pegas ficarem a meio do peito.",
      "Empurra sem travar os cotovelos com força.",
      "Omoplatas encostadas ao apoio.",
    ],
  },
  {
    slug: "face-pull",
    source: "Face_Pull",
    name: "Face Pull na Polia",
    muscle: "ombros",
    family: "accessory",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "Polia à altura da cara.",
      "Puxa a corda em direcção aos olhos, mãos a abrir no fim.",
      "Peso leve e muitas repetições: isto é para a saúde do ombro.",
    ],
  },
  {
    slug: "triceps-pushdown",
    source: "Triceps_Pushdown",
    name: "Extensão de Tríceps na Polia",
    muscle: "tríceps",
    family: "accessory",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "Cotovelos fixos junto ao corpo do princípio ao fim.",
      "Estica por completo e volta só até aos 90 graus.",
      "Tronco direito, sem te deitares sobre a barra.",
    ],
  },
  {
    slug: "calf-raise",
    source: "Standing_Calf_Raises",
    name: "Elevação de Gémeos",
    muscle: "gémeos",
    family: "accessory",
    increment: 5,
    profiles: ["full_gym"],
    cues: [
      "Alongamento total em baixo, contracção total em cima.",
      "Um segundo de pausa no topo de cada repetição.",
      "Joelhos esticados mas não travados.",
    ],
  },
  {
    slug: "cable-crunch",
    source: "Cable_Crunch",
    name: "Abdominal na Polia",
    muscle: "abdominais",
    family: "accessory",
    increment: 2.5,
    profiles: ["full_gym"],
    cues: [
      "Ajoelha longe o suficiente para sentires tensão no início.",
      "Enrola as costelas em direcção à anca; a anca não se mexe.",
      "Volta devagar em vez de te deixares puxar.",
    ],
  },

  /* ---------------------------------------------------- peso do corpo */
  {
    slug: "pull-up",
    source: "Pullups",
    name: "Elevações na Barra",
    muscle: "dorsais",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Braços esticados em baixo, ombros activos.",
      "O queixo passa a barra sem esticar o pescoço.",
      "Usa elástico ou máquina assistida enquanto ganhas força.",
    ],
  },
  {
    slug: "chin-up",
    source: "Chin-Up",
    name: "Elevações Supinadas",
    muscle: "bíceps",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym", "home_minimal"],
    cues: [
      "Palmas viradas para ti, mãos à largura dos ombros.",
      "Puxa os cotovelos para baixo, em direcção às costelas.",
      "Controla a descida; é aí que ganhas força.",
    ],
  },
  {
    slug: "dip",
    source: "Dips_-_Triceps_Version",
    name: "Fundos de Tríceps",
    muscle: "tríceps",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym"],
    cues: [
      "Tronco quase vertical, cotovelos a apontar para trás.",
      "Desce até os braços ficarem paralelos ao chão.",
      "Pára a série se a frente do ombro picar.",
    ],
  },
  {
    slug: "push-up",
    source: "Pushups",
    name: "Flexões de Braços",
    muscle: "peito",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym", "hotel", "home_minimal"],
    cues: [
      "Corpo em linha recta da cabeça aos calcanhares; aperta os glúteos.",
      "Cotovelos a cerca de 45 graus, não abertos de lado.",
      "Peito ao chão e empurra o chão para longe.",
    ],
  },
  {
    slug: "bodyweight-squat",
    source: "Bodyweight_Squat",
    name: "Agachamento Livre",
    muscle: "quadríceps",
    family: "bodyweight",
    increment: 0,
    profiles: ["hotel", "home_minimal"],
    cues: [
      "Pés à largura dos ombros, pontas ligeiramente para fora.",
      "Ancas para trás e para baixo, calcanhares no chão.",
      "Devagar a descer, três segundos.",
    ],
  },
  {
    slug: "walking-lunge",
    perSide: true,
    source: "Bodyweight_Walking_Lunge",
    name: "Afundo a Andar",
    muscle: "quadríceps",
    family: "bodyweight",
    increment: 0,
    profiles: ["hotel", "home_minimal"],
    cues: [
      "Passos largos, tronco direito.",
      "O joelho de trás toca ao de leve no chão.",
      "Conta as repetições por perna, não no total.",
    ],
  },
  {
    slug: "glute-bridge",
    source: "Butt_Lift_Bridge",
    name: "Ponte de Glúteos",
    muscle: "glúteos",
    family: "bodyweight",
    increment: 0,
    profiles: ["hotel", "home_minimal"],
    cues: [
      "Calcanhares perto dos glúteos, pontas dos pés levantadas.",
      "Empurra com os calcanhares e aperta no topo.",
      "Costelas em baixo: não arqueies a lombar.",
    ],
  },
  {
    slug: "inverted-row",
    source: "Inverted_Row",
    name: "Remada Invertida",
    muscle: "costas",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym", "hotel", "home_minimal"],
    cues: [
      "Corpo em linha recta, calcanhares no chão.",
      "Puxa o peito à barra ou ao rebordo da mesa.",
      "Aproxima os pés do corpo para ficar mais fácil.",
    ],
  },
  {
    slug: "pike-push-up",
    source: "Pushups",
    name: "Flexões Pique",
    muscle: "ombros",
    family: "bodyweight",
    increment: 0,
    profiles: ["hotel", "home_minimal"],
    cues: [
      "Ancas altas, corpo em V invertido.",
      "Desce o topo da cabeça em direcção ao chão.",
      "Põe os pés numa cama ou cadeira para ficar mais difícil.",
    ],
  },
  {
    slug: "plank",
    timed: true,
    source: "Plank",
    name: "Prancha",
    muscle: "abdominais",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym", "hotel", "home_minimal"],
    cues: [
      "Cotovelos debaixo dos ombros, antebraços no chão.",
      "Aperta os glúteos e mete as costelas para baixo.",
      "Aguenta o tempo indicado; pára quando a anca começa a cair.",
    ],
  },
  {
    slug: "side-plank",
    timed: true,
    source: "Side_Bridge",
    name: "Prancha Lateral",
    muscle: "abdominais",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym", "hotel", "home_minimal"],
    cues: [
      "Cotovelo debaixo do ombro, corpo em linha.",
      "Levanta a anca e aguenta, a respirar normalmente.",
      "Tempo igual dos dois lados.",
    ],
  },
  {
    slug: "hanging-leg-raise",
    source: "Hanging_Leg_Raise",
    name: "Elevação de Pernas Suspenso",
    muscle: "abdominais",
    family: "bodyweight",
    increment: 0,
    profiles: ["full_gym"],
    cues: [
      "Pendurado sem balançar.",
      "Enrola a bacia para cima em vez de só levantar as pernas.",
      "Dobra os joelhos para ficar mais fácil.",
    ],
  },
  {
    slug: "mountain-climber",
    source: "Mountain_Climbers",
    name: "Escalador",
    muscle: "abdominais",
    family: "bodyweight",
    increment: 0,
    profiles: ["hotel", "home_minimal"],
    cues: [
      "Mãos debaixo dos ombros, ancas ao nível do tronco.",
      "Leva os joelhos ao peito, um de cada vez.",
      "Ritmo constante; a anca não salta.",
    ],
  },
  {
    slug: "superman",
    timed: true,
    source: "Superman",
    name: "Superman",
    muscle: "lombar",
    family: "bodyweight",
    increment: 0,
    profiles: ["hotel", "home_minimal"],
    cues: [
      "De barriga para baixo, braços esticados à frente.",
      "Levanta o peito e as coxas apenas alguns centímetros.",
      "Olha para o chão para manter o pescoço neutro.",
    ],
  },
];
